services:
  database:
    image: postgres
    container_name: trabalho-dev-web-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - trabalho-dev-web:/var/lib/postgresql/data
    networks:
      - trabalho-dev-web

  tomcat:
    image: tomcat:latest
    container_name: trabalho-dev-web-tomcat
    ports:
      - "8080:8080"
    volumes:
      - ./src/main/webapp:/usr/local/tomcat/webapps/ROOT
    env_file:
      - .env
    working_dir: /app
    depends_on:
      - database
    networks:
      - trabalho-dev-web

volumes:
  trabalho-dev-web:

networks:
  trabalho-dev-web: