services:
  app:
    build: .
    container_name: trabalho-dev-web-app
    ports:
      - "8080:8080"
    depends_on:
      - database
    volumes:
      - ./src/main/webapp:/usr/local/tomcat/webapps/ROOT
      - ./target/classes:/usr/local/tomcat/webapps/ROOT/WEB-INF/classes

    networks:
      - trabalho-dev-web

  database:
    image: postgres
    container_name: trabalho-dev-web-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - trabalho-dev-web:/var/lib/postgresql/data
    networks:
      - trabalho-dev-web

volumes:
  trabalho-dev-web:

networks:
  trabalho-dev-web:
