services:
  app:
    build: .
    container_name: trabalho-dev-web
    ports:
      - 8080:8080
    depends_on:
      - database
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=trabalho_dev_web
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - .:app

  database:
    image: postgres
    container_name: trabalho-dev-web-database
    restart: always
    environment:
      POSTGRES_DB: trabalho_dev_web
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5434:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: