services:
  app:
    image: mcr.microsoft.com/devcontainers/java:17
    container_name: trabalho-dev-web-app
    volumes:
      - ../:/workspaces/trabalho-dev-web:cached # Montar o diretório no container remoto
    env_file:
      - ./.env
    networks:
      - trabalho-dev-web
    command: sleep infinity

  database:
    image: postgres
    container_name: trabalho-dev-web-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - trabalho-dev-web_db:/var/lib/postgresql/data
      - ../init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - trabalho-dev-web

volumes:
  trabalho-dev-web_db:

networks:
  trabalho-dev-web: